### ISSUE TITLE
Handle datatypes for allowed values

### ISSUE THREAD

**Issue by jdacoello** [COVESA/s2dm#8]
VSS allows the specification of any datatype for allowed values. 
```yaml
FuelType:
  type: attribute
  allowed: ["DIESEL","E10","E5"]
  datatype: string
  ...

Gear:
  type: sensor
  allowed: [1,2,3,4,5]
  datatype: int
```

GraphQL, however represents values of enums as String:
```
enum GearEnum {
  _1
  _2
  _3
}
```
The revolvers can map the enum to any datatype. 

--
How to handle that?
